const BASE_URL = "http://localhost:4000";

const handleResponse = async (res: Response) => {
    if (!res.ok) {
        const text = await res.text();
        console.error(`API Error: ${res.status} ${res.statusText}`, text);
        try {
            const json = JSON.parse(text);
            throw new Error(json.message || res.statusText);
        } catch (e) {
            // If the error we just threw is what caught us, rethrow it
            if (e instanceof Error && e.message !== "Invalid JSON") {
                // To distinguish between JSON.parse error and our custom error, 
                // typically we check if the error was generated by us.
                // Simpler approach: check if text looks like JSON or just rely on the first error.
                if (text.trim().startsWith('{') || text.trim().startsWith('[')) {
                    throw new Error(JSON.parse(text).message || res.statusText);
                }
            }
            console.error("API Error (Non-JSON):", text);
            throw new Error(`API Request Failed: ${res.status} ${res.statusText}`);
        }
    }
    return res.json();
};

export const api = (token: string) => {
    const headers = {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
    };

    return {
        getMe: () =>
            fetch(`${BASE_URL}/auth/me`, { headers }).then(handleResponse),

        getUsers: () =>
            fetch(`${BASE_URL}/users`, { headers }).then(handleResponse),

        getTasks: () =>
            fetch(`${BASE_URL}/tasks`, { headers }).then(handleResponse),

        createTask: (data: { title: string; description?: string; assignedTo?: string; deadline?: string }) =>
            fetch(`${BASE_URL}/tasks`, {
                method: "POST",
                headers,
                body: JSON.stringify(data),
            }).then(handleResponse),

        updateTaskStatus: (taskId: string, status: string) => {
            console.log('Updating task status:', { taskId, status, token: token.substring(0, 20) + '...' });
            return fetch(`${BASE_URL}/tasks/${taskId}/status`, {
                method: "PATCH",
                headers,
                body: JSON.stringify({ status }),
            }).then(handleResponse);
        },

        deleteTask: (taskId: string) =>
            fetch(`${BASE_URL}/tasks/${taskId}`, {
                method: "DELETE",
                headers,
            }).then(handleResponse),
    };
};
